
# Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
# Click nbfs://nbhost/SystemFileSystem/Templates/Other/properties.properties to edit this template

db.url=jdbc:sqlserver://localhost:1433;databaseName=LearningPathDB;encrypt=true;trustServerCertificate=true;
db.user=sa
db.password=123