package org.swp.my_learning_path.constant;

public enum EFileType {
    VIDEO,          // mp4, avi, mov,...
    SUBTITLE,       // srt, vtt,...
    IMAGE,          // jpg, jpeg, png, gif, webp,...
    DOCUMENT
}
