# Server config
server.port=8080
# Application name
spring.application.name=My_Learning_Path

# Datasource config
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=SWP_final_project;encrypt=true;trustServerCertificate=true;
spring.datasource.username=sa
spring.datasource.password=123
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
logging.level.org.springframework.security=DEBUG

# JPA & Hibernate config
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# SQL Initialization
#chay lan dau thì always, chay lan 2 tr di thì  never
#spring.sql.init.mode=always
spring.sql.init.mode=never
spring.jpa.defer-datasource-initialization=true

#DEVTOOLS
spring.devtools.restart.enabled=true
spring.devtools.livereload.enabled=true

#Thymeleaf
#spring.thymeleaf.prefix=classpath:/templates/
#spring.thymeleaf.suffix=.html
#spring.thymeleaf.cache=true
#bảo mật key cá nhân
spring.profiles.include=secret
# Cấu hình không bảo mật của S3
aws.s3.bucket-name=hung-he-191035
aws.region=ap-southeast-2
# Tang gioi han dung luong upload file video len 500MB
spring.servlet.multipart.max-file-size=500MB
spring.servlet.multipart.max-request-size=500MB